### ISSUE TITLE
Error: Bad Content-Type and .zip.cpgz

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/archivers-zip-starter#1]
Hey, just trying to use this and walk through the pipeline workflow. When I follow readme exactly I'm entering:

```
curl -d "{ \"uuid\" : \"test-zip-starter\", \"url\" : \"http://www.epa.gov\"}" http://localhost:3000 > test-zip-starte2.zip
```

I get an error
```
POST - 2017-01-31 22:18:28.724590779 -0500 EST - /
Bad Content-Type: 'application/x-www-form-urlencoded'
```
When extracting the file I get
```
-rw-r--r--   1 <>    44 31 Jan 22:18 test-zip-starter.zip
-rw-r--r--   1 <>   176 31 Jan 22:19 test-zip-starter.zip.cpgz
```

I've only run into `.zip.cpgz` with improperly generated/compressed files? 

I'm not super familiar with that is going on here, or go tbh. If this is expected output can we document?

**Comment by dcwalk** [comment]
Just an update--- I actually _followed the instructions_ (it's late), and got the same error, and `.zip.cpgz` generated from a formlerly function `.zip` with a real example:
```
curl -d "{ \"uuid\" : \"11B7B7F8-23B6-4E69-8EE4-3098B470B095\", \"url\" : \"https://www.st.nmfs.noaa.gov/marine-mammals-turtles/database/index\"}" http://localhost:3000 > 11B7B7F8-23B6-4E69-8EE4-3098B470B095.zip
```

```
-rw-r--r--@  1 <>    44 31 Jan 23:11 11B7B7F8-23B6-4E69-8EE4-3098B470B095.zip
-rw-r--r--   1 <>   398 31 Jan 23:11 11B7B7F8-23B6-4E69-8EE4-3098B470B095.zip.cpgz
```

I'm too unfamiliar with this stuff to troubleshoot

**Comment by b5** [comment]
lol I was a little foggy when I wrote those instructions. I'll have a look and fix

**Comment by dcwalk** [comment]
Closing as this isn't super necessary now that we have moved to https://github.com/datatogether
