### ISSUE TITLE
Distribute binary/executable?

### ISSUE THREAD

**Issue by dcwalk** [edgi-govdata-archiving/archivers-zip-starter#3]
It would be great to allow people to use this without requiring go installed on their system. I'm thinking that is just another dependencies/barrier to getting people up and running at an event.

Is there a way we can distribute prebuilt binaries?

Looking [go.17 release notes](https://tip.golang.org/doc/go1.7) I'm thinking, sorta possible?
Caveat, I don't use go!

**Comment by b5** [comment]
This sounds like a _very_ good idea. It'll take some time to get back around to it (soooooo much on the go atm), but I'll try to loop back in a week or two & setup some sort of release-binary-builder thing for any/all of the repos on here that are written in go.

and I'll just leave this here..... https://tour.golang.org ;)

**Comment by atesgoral** [comment]
Or Dockerize it? Or even [Whalebrew](https://github.com/bfirsh/whalebrew)?

**Comment by ChaiBapchya** [comment]
I myself have been using Go as part of my previous project. Documentation is pretty useful. https://golang.org/doc/install
Don't see any issue keeping a dependency of Go. (need not be on priority I mean)

**Comment by dcwalk** [comment]
Closing out as we've moved to https://github.com/datatogether/, which is very dockerized!
